---
- name: Read users from CSV file and return a list
  community.general.read_csv:
    path: files/nodes.csv
#    key: host_name
  register: nodes
  delegate_to: localhost

- name: Create a new host or update an existing host's info
  local_action:
    module: community.zabbix.zabbix_host
    server_url: http://10.53.5.81/zabbix
    login_user: Admin
    login_password: zabbix
    host_name: ExampleHost
    host_groups:
      - 01_Network
    link_templates:
      - 01_ICMP_5min
    status: enabled
    state: present
    interfaces:
      - type: "1"
        main: "1"
        useip: "1"
        ip: "10.53.5.1"
        dns: ""
        port: "10050"

- name: debug csv
  debug:
#    msg: "{{ nodes }}"
#    msg: 'Node {{ nodes.dict.sv01.host_name }} has IP {{ nodes.dict.sv01.ip_addr }}'
    msg: "{{ nodes.list.0.host_name }} Is {{ nodes.list.0.ip_addr }}"
#   msg: 'User {{ users.dict.dag.name }} has UID {{ users.dict.dag.uid }} and GID {{ users.dict.dag.gid }}'

