---
- name: Create host groups
  community.zabbix.zabbix_group:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    host_groups:
      - "{{ zabbix_hostgroup01 }}"
      - "{{ zabbix_hostgroup02 }}"
      - "{{ zabbix_hostgroup03 }}"

- name: Read users from CSV file and return a list
  become: true
  community.general.read_csv:
    path: files/nodes.csv
    fieldnames: host_name,host_group,ip_addr,template
  register: nodes
  delegate_to: localhost

- name: debug csv
  debug:
    msg: "{{ nodes }}"

- name: Create a new host or update an existing host's info
#  local_action:
#    module: community.zabbix.zabbix_host
  community.zabbix.zabbix_host:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    host_name: "{{ item.host_name }}"
    host_groups: "{{ item.host_group }}"
    link_templates: "{{ item.template }}"
    status: enabled
    state: present
    interfaces:
      - type: "1"
        main: "1"
        useip: "1"
        ip: "{{ item.ip_addr }}"
        dns: ""
        port: "10050"
  with_items: "{{ nodes.list }}"


