---
- name: Import Zabbix templates from XML 1
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    template_xml: "{{ lookup('file', '01_ICMP_5min.xml') }}" 
    state: present

- name: Import Zabbix templates from XML 2
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    template_xml: "{{ lookup('file', '02_ICMP_1min.xml') }}"
    state: present

- name: Import Zabbix templates from XML 3
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    template_xml: "{{ lookup('file', '03_ICMP_15min.xml') }}" 
    state: present
