---
- name: Create host groups
#  become: true
#  local_action:
#  module: community.zabbix.zabbix_group
  community.zabbix.zabbix_group:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    state: present
    host_groups:
      - "{{ zabbix_hostgroup01 }}"
      - "{{ zabbix_hostgroup02 }}"
      - "{{ zabbix_hostgroup03 }}"
