---
- name: upgrade pip
  become: true
  pip:
    executable: pip3
    state: latest
    name:
      - zabbix-api

- name: Create user group with disabled gui access
  become: yes
  community.zabbix.zabbix_usergroup:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    name: Alert
    state: present
    gui_access: disable

- name: create a new zabbix user and media.
  community.zabbix.zabbix_user:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    alias: Alert
    usrgrps:
      - Alert
    passwd: "{{ zabbix_login_password }}"
    lang: ja_JP
    user_medias:
      - mediatype: Email
        sendto: "{{ zabbix_alert_email }}"
        period: 1-7,00:00-24:00
        severity:
          not_classified: no
          information: no
          warning: yes
          average: yes
          high: yes
          disaster: yes
        active: yes
    type: Zabbix super admin
    state: present

- name: create a new zabbix Admin user.
  community.zabbix.zabbix_user:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_login_user }}"
    login_password: "{{ zabbix_login_password }}"
    alias: SuperUser
    usrgrps:
      - "Zabbix administrators"
    passwd: "{{ zabbix_admin_password }}"
    lang: ja_JP
    type: Zabbix super admin
    state: present
